/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ArticlePagination: typeof import('./src/components/ArticlePagination.vue')['default']
    ArticlePreview: typeof import('./src/components/ArticlePreview.vue')['default']
    ArticleToggle: typeof import('./src/components/ArticleToggle.vue')['default']
    AuthPage: typeof import('./src/components/AuthPage.vue')['default']
    ContaList: typeof import('./src/components/ContaList.vue')['default']
    ContaPreview: typeof import('./src/components/ContaPreview.vue')['default']
    ContaToggle: typeof import('./src/components/ContaToggle.vue')['default']
    CreditaContaButton: typeof import('./src/components/CreditaContaButton.vue')['default']
    DeleteArticleButton: typeof import('./src/components/DeleteArticleButton.vue')['default']
    DeleteContaButton: typeof import('./src/components/DeleteContaButton.vue')['default']
    EditArticleButton: typeof import('./src/components/EditArticleButton.vue')['default']
    EditContaButton: typeof import('./src/components/EditContaButton.vue')['default']
    ErrorMessages: typeof import('./src/components/ErrorMessages.vue')['default']
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TransfereContaButton: typeof import('./src/components/TransfereContaButton.vue')['default']
  }
}
